# --- pyproject.toml ---

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "codegrapher-ai"
version = "0.1.0"
description = "An AI agent for code analysis using RAG and agents."
requires-python = ">=3.9"

# --- FIX: Add this new section to be explicit about our code ---
[tool.setuptools]
# List the standalone .py files in the root that are modules
py-modules = ["config", "logging_config"]
# List the directories that are Python packages
packages = ["engine", "tools"]